### PR TITLE
Change Rack server from thin to unicorn for greater performance

### PR DESCRIPTION
**Pull request by deathowl**
Attached AB results:
Thin with one worker:
deathowl:~/ (master✗) $ ab -n 100 -c 10 -r  http://127.0.0.1:3000/                                                                                                      [20:57:12]
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)...Send request failed!
Send request failed!
..done

Server Software:        thin
Server Hostname:        127.0.0.1
Server Port:            3000

Document Path:          /
Document Length:        31424 bytes

Concurrency Level:      10
Time taken for tests:   131.099 seconds
Complete requests:      100
Failed requests:        3
   (Connect: 0, Receive: 1, Length: 2, Exceptions: 0)
Write errors:           2
Total transferred:      3176786 bytes
HTML transferred:       3118586 bytes
Requests per second:    0.76 [#/sec](mean)
Time per request:       13109.925 [ms](mean)
Time per request:       1310.993 [ms](mean, across all concurrent requests)
Transfer rate:          23.66 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0 10123 4009.8  11487   19334
Processing:     0 2586 1574.8   2583    5405
Waiting:        0  351 1171.7      0    4302
Total:       1439 12709 3625.7  13546   19334

Percentage of the requests served within a certain time (ms)
  50%  13546
  66%  14208
  75%  15166
  80%  15306
  90%  16129
  95%  17240
  98%  17916
  99%  19334
 100%  19334 (longest request)

Unicorn with one worker ( number of workers is changeable with the UNICORN_WORKERS env var):
deathowl:~/ (master✗) $ ab -n 100 -c 10 -r  http://127.0.0.1:3000/                                                                                                      [20:56:50]
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)...Send request failed!
Send request failed!
Send request failed!
Send request failed!
Send request failed!
Send request failed!
..done

Server Software:
Server Hostname:        127.0.0.1
Server Port:            3000

Document Path:          /
Document Length:        31424 bytes

Concurrency Level:      10
Time taken for tests:   10.020 seconds
Complete requests:      100
Failed requests:        5
   (Connect: 0, Receive: 1, Length: 4, Exceptions: 0)
Write errors:           6
Total transferred:      3051028 bytes
HTML transferred:       2992424 bytes
Requests per second:    9.98 [#/sec](mean)
Time per request:       1002.014 [ms](mean)
Time per request:       100.201 [ms](mean, across all concurrent requests)
Transfer rate:          297.35 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0  854 272.7    887    2116
Processing:     0  114 469.4      0    2116
Waiting:        0  116 469.1      0    2115
Total:        466  968 313.7    890    2116

Percentage of the requests served within a certain time (ms)
  50%    890
  66%    910
  75%    917
  80%    933
  90%   1110
  95%   2116
  98%   2116
  99%   2116
 100%   2116 (longest request)

### CODE REVIEW

**Comment by fdietz** [comment]
Hi!

using unicorn vs thin (especially on heroku where you have only a single dyno) makes definitely sense.

First time I see this unicorn-rails gem. But, I think whats missing is the unicorn configuration file. If you use more than a single worker than you have child processes forked from the master and these must reconnect to the database explicitly. 

Here's some more background information:
https://blog.heroku.com/archives/2013/2/27/unicorn_rails

Cheers,
Frederik

**Comment by deathowl** [comment]
I'll change from the unicorn-rails gem to the plain unicorn solution. I'll notify you when it's done,

**Comment by deathowl** [comment]
i changed the setup from unicorn-rails to plain unicorn.

**Comment by fdietz** [comment]
Cool! Will look into it. I'm having troubles getting kgio gem to compile. Need to fix my ruby install first.

**Comment by fdietz** [comment]
Hi again!

I've merged your changes!

https://github.com/fdietz/team_dashboard/commit/07e3dba56b7b1235a61ba0b2bcec76353cf721dd

Thanks a lot!
Frederik

**Comment by fdietz** [comment]
I had to do slight adjustments but now it also works on heroku!

**Comment by deathowl** [comment]
Great news! 
Thanks!

**Pull request closed without merging**
