### PR TITLE
New FileInput widget

### PR DESCRIPTION
**Pull request by paulhamby**
I had previously created pull request https://github.com/fdietz/team_dashboard/pull/83, however, I think this is a better solution.

Notes:
There are some files that I've dropped into the "vendor" directory, not sure this is the proper spot for these files.
I've added "overflow: hidden" to app/assets/stylesheets/application.css.less in order to get the behavior I need; I'm curious if that is undesired.

Hope you dig it, it's working for us and solves a need we have!

### CODE REVIEW

**Comment by paulhamby** [comment]
Hi,

Let me know if there is anything I can change/add to get this merged.

Thanks!
Paul

**Comment by fdietz** [comment]
Hi Paul,

sorry for answering that late. My job kept me quite busy and away from my open source projects!

I actually find your idea with the file as source very useful. But, I more prefer the way it was integrated in #83, since it was a nice reusable source plugin. The widget you created seems very specific to one particular use case.

Let me elaborate. As a user, it is obvious how a graph widget will most probably look like, or a number widget. And that they can both display information from various source plugins in different ways. But a file input widget does not describe how it presents something. 

My goal is to have only a handful of useful widgets but lots of source plugins for them. It might even make sense to make the alert widget more flexible.

I'd love to use your idea of the file input for all widgets including boolean, number, alert, etc. by creating source plugins for each of these widget types instead. What do think of that?

Sorry again for answering that late.

Cheers,
Frederik

**Comment by paulhamby** [comment]
Hi Frederik,

No worries on the time to reply. I get what you are saying and I agree.

I implemented it as a widget because I wasn't sure if I could get the features I wanted without making possibly undesired changes to the alert widget. I want to be able to display data from a file in table format and I would like to be able to have the size of the widget be fairly large, if possible. If those features still fit well within the alert widgets purpose, then I can work on implementing them. If not, then perhaps a "table" widget with a file input would be a possibility?

Thanks!
Paul

**Comment by fdietz** [comment]
Hi again Paul!

I've been thinking about this widget idea of yours and talked with a site ops friend of mine about this. Your use case reminds me quite a bit of nagios alerts where you have usually a whole list of of alerts and an overall system status. I didn't quite get your initial idea because you didn't list the status for each row. So, I'm reconsidering my initial response!

Let me propose a widget hopefully more in line of what you want to achieve, but with a minor tweak! Let's call it "status table" widget or something similar. And add a status row to the table and put the overall status on top, looking similar to this screenshot:

screen shot 2013-07-20 at 12 55 45 pm

My primary goal with team dashboard is to have widgets which you can view easily on a large screen. That's why it would be nice to have the overall status with one of the errors on top in a larger font size (22px) and the table underneath with a slightly smaller size. I've tested this with a 40" screen standing 3 meters. Even though it starts to become difficult to read all individual lines, one can easily read the overall status, and its easy to spot status for each row. That makes the table more usable for a large screen setup in my opinion.

I have not solved yet how to manage too many rows to fit into the widget, but using overflow:hidden for now is good start.

Additionally, I'd add the generic http proxy source plugin so anyone with a json service could use that widget too. 

This is hopefully also almost exactly what you wanted to achieve. Isn't it? What do you think?

**Comment by paulhamby** [comment]
Sounds good to me! Is "status table" the name we want to go with?

**Comment by fdietz** [comment]
"Status Table" is okay with me!

Can you look into your json format again, please? It looks like you are
mixing upper/lower case keys. I suggest to use one or the other.

And don't forget to include your widget in the README and add yourself to
the list of contributors!

**Comment by paulhamby** [comment]
I've added the new status_table widget with row level status. However, instead of having the first item displayed next to the overall status indicator being one of the items from the list, I've got it displaying widget.name for now. A challenge that I'm having with it displaying one of the items for the list is choosing which item to display. For instance, if the overall status is red, but I happen to display an item whose individual status is green, this could be confusing. I'm interested in your opinion on what would be best to display there.

Thanks!
Paul

image

**Comment by fdietz** [comment]
Hi again,

I'd choose one (random) of the red items, if the status is red. That would
be the easiest to do. Additionally, other source plugins could choose a
different strategy. The sample method of the array class would be an easy
way to achieve this, given that you have an array of all the items with a
red status.

BTW, it would be cool to move all the json generation code into the base
class. That way your file input, and the http proxy call I'd like to add
only need to implement the reading of the input source.

I can assist with the css stuff based on my mockup, since I got that
already sitting on my harddrive.

Cheers,
Frederik

**Comment by paulhamby** [comment]
Hi Frederik,

I've got it selecting an appropriate event now to display next to the overall status indicator. Do you think you might be able to help me out with what you want moved into the base class? It's not clear to me what should belong in the base and what shouldn't.

Thanks!
Paul

**Comment by fdietz** [comment]
Hi again,

no problem, I can do that! Are you finished from your side, so I  can I
merge it now?

Cheers,
Frederik

**Comment by paulhamby** [comment]
Yes, I'm done from my side, so merge away!

Thanks!
Paul

**Comment by fdietz** [comment]
I've merged the code! 

Additionally, I've moved the shared code of demo/json_input/http_proxy into the base class. The http proxy source is useful for people who have a service running instead of accessing a local file.

**Pull request closed without merging**
