### PR TITLE
Pingdom Plugin

### PR DESCRIPTION
**Pull request by DraganMileski**
Hallo Frederik,

I created Pingdom data source for the Boolean widget. Please have a look and share it if you like it. I hope that it will be useful for other people. For now is just the first version. I have free pingdom account with just one check so for that it works perfectly :) If you have any suggestions for making it better please contact me and we can discuss it :) Enjoy

LG,
Dragan Mileski

### CODE REVIEW

**Comment by DraganMileski** [comment]
There was a minor bug with the check name i think i resolve it. The password field has to be made masked as well

**Comment by fdietz** [comment]
Hi Dragan!

thanks for looking into implementing a Pingdom plugin! I'd love to add this to the team_dashboard_plugins repository for others to use. 

There's only one thing I'd like you to look into again. There's already the faraday gem in place to do http request and the class HttpService:
https://github.com/fdietz/team_dashboard/blob/master/app/models/http_service.rb

I'd gives us a central place for configuring the http connection including ssl, https, authentication, etc. without doing it for various libraries.

So, if you would be able to change that to use the existing HttpService that would simplify the integration for others.

Kind regards,
-Frederik

**Comment by fdietz** [comment]
Hi again,

I forgot another thing, you could look into. The user/password field are probably a global configuration, since a user has a single account. Why not move this configuration to the environment/rails config instead.

There's documentation on the plugin repo readme on how to do that:
https://github.com/fdietz/team_dashboard_plugins

Cheers,
-Frederik

**Comment by DraganMileski** [comment]
I forgot to mention in the commit message that i set the Pingdom username and the password as environmental variables.

**Comment by fdietz** [comment]
Hi Dragan,

I've pushed your pingdom plugin to the plugin repository (that's why I can't merge it from here, it is a different repository).

If you have further ideas/changes it would be more convenient to patch them there!

Here's the commit:
https://github.com/fdietz/team_dashboard_plugins/commit/7e3d3adc038b6c79c0a03660585f5c06e1463686

Many thanks!
-Frederik

**Pull request closed without merging**
