### PR TITLE
Added a file source to the alert module

### PR DESCRIPTION
**Pull request by paulhamby**
Hi,

I've added a file source to the alert module to fit my needs. It expects a JSON file with the fields: "Value", "Label" and "status". I've shamelessly ripped off several code snippets from the sensu alert source.

-Paul

### CODE REVIEW

**Comment by fdietz** [comment]
Hi Paul,

interesting idea to use a json file as input! I like it! I'm curious about your use case. Do you have a service which generates/changes the file content?

Also, in order to get merged can you please provide a testcase?

Cheers,
Frederik

**Comment by paulhamby** [comment]
Yeah, there is a separate script fired off via cron which queries a database for the interesting information and spits out a file in the expected format.

I'll see if I can get a test together. This is my first attempt at writing in Ruby, so it may take a bit :)

-Paul

**Comment by fdietz** [comment]
There are some tests available already, for example: 
https://github.com/fdietz/team_dashboard/blob/master/spec/models/sources/ci/travis_spec.rb
https://github.com/fdietz/team_dashboard/blob/master/spec/models/sources/number/jira_filter_count_spec.rb

Let me know if you get it working, otherwise I can assist you!

**Comment by paulhamby** [comment]
I think pull request #102 does a better a job of implementing this functionality.

**Pull request closed without merging**
