### PR TITLE
Introducing the Alert widget with a Sensu datasource

### PR DESCRIPTION
**Pull request by DraganMileski**

### CODE REVIEW

**Comment by fdietz** [comment]
Awesome! First new angular.js based contributed widget!

**Comment by wangwensheng** [comment]
can you tell me how to use this alert widget, it would be best to show some examples when i have already install sensu, team_dashboard.thanks!

**Comment by fdietz** [comment]
The easiest approach is to start Team Dashboard with the environment variable:
SENSU_EVENTS_URL=http://localhost:8080 rails server

Then create a dashboard with a widget of type "alert" and select "sensu" as the source.

For any further details you can additionally get in touch with Dragan Mileski, the author of the widget.

Cheers!

**Comment by DraganMileski** [comment]
Hey Irving

Question: Should you use the sensu API port (typically 4567) or the sensu

> dashboard port(typically port 8080)?
> 
> you should use the sensu API port 4567. So when you start the rails app you
> should start it with the SENSU_EVENTS_URL=http://<your_sensu_host>:4567
> 
> Also I'm seeing errors when the client and/or check filters are empty.
> like so:
> 
> Started GET "/api/data_sources/alert?source=sensu&widget_id=15" for
> 10.0.2.2 at 2013-05-07 11:32:28 -0700
> Processing by Api::DataSourcesController#index as JSON
> Parameters: {"source"=>"sensu", "widget_id"=>"15", "kind"=>"alert"}
> Widget Load (0.3ms) SELECT widgets.\* FROM widgets WHERE widgets.id = 15
> LIMIT 1
> Internal Server Error: #
> /home/vagrant/team_dashboard-master/app/models/sources/alert/sensu.rb:22:in
> fetch'
> /home/vagrant/team_dashboard-master/app/models/sources/alert/sensu.rb:22:in
> get'
> 
> anyone else seeing this?
> 
> —

That is true. It is a bug that has to be fixed. The point is that since the
filter keys are optional we should use hash[key] instead of fetch. This
will return nil if the key does not exist. The point by leaving empty
filters is that by default you will receive all system events. And if you
want to visualize special subset than you filter it.

This days I am very busy. My 4th semester in TUM is eating my whole time.
However I will try to find some time to fix this thing in the next days. I
also have to provide RSpec test for it...

Before I fix it you can simply, type something and then delete it. This
initializes the key filter and it works afterwards :)

**Comment by wangwensheng** [comment]
thank you very much! but when i start team dashboard like this: GRAPHITE_URL=http://localhost:8080/ SENSU_EVENTS_URL=http://localhost:8081/ rails s , then team dashborad crashed. it can not connect with graphite, and i start team dashboard like this:GRAPHITE_URL=http://localhost:8080/ rails s , it shows correctly, What has caused this phenomenon, and how to use it in the right way, thanks.

**Comment by DraganMileski** [comment]
Try without a slash at the end: 
GRAPHITE_URL=http://localhost:8080/ SENSU_EVENTS_URL=http://localhost:4567 rails s

If it works then i have to change the code a bit :) Also make sure that you use 4567 as a port because i think that this is the right one.

**Comment by wangwensheng** [comment]
yes, it works when i use the way you provide! but i really have no idea how to use alert widget, for example , how to set parameter "Filter by clients"、"Ignore checks" :)

**Comment by DraganMileski** [comment]
well if you live it empty than it gives you result of all checks from the
curent system (imagine you have bigger network with several sensu clients).
In such a case there you have the possibility to just put several clients
(client_name1,client_name2,client_name3) divided by comma, and display only
the results for those (small subnetwork for example). That was the idea
behind filter by clients.

On the other hand you might have configured some checks that are sending
you warnings and errors that are not relevant at the moment for you. For
example some of your clients is down for few hours maintenance but sensu
sees it as error and alerts you all the time. In that case you might want
to ignore few checks by typing:

your_client_name1:your_check_name1;your_client_name1:your_check_name3,your_client_name2:your_check_name5;
Please make sure you use colon and semicolon as I in the example.

Good Luck

**Comment by aberrios85** [comment]
I plan on adding an extra field to the sensu alert to only take into account sensu clients that match a regex supplied by the user..

I have a working method so I can say I only want to see alerts from sensu that match client name regex ^IC03.  therefore alert widget ignores any warnings from clients that don't start IC03.....

Will submit PR if anyone else wants this.

**Pull request merged**
