### PR TITLE
adding CI Provider for TeamCity 8.1.x

### PR DESCRIPTION
**Pull request by leifhanack**
Hi Frederik,

I added a TeamCity CI provider. 

It is unit tested as well as manually tested against TeamCity 8.1.x. 

If you want to verify it you can download TeamCity for free. In order to use the TeamCity REST API without credentials you have to enable guest access. 

You should configure the widget with the TeamCity host (e.g. `http://localhost:8111` without trailing `/`) and the project id. If you hover a project in TeamCity you see a link like `http://localhost:8111/project.html?projectId=peeone&tab=projectOverview`. In that example `peeone` is the project name that needs to be configured when setting up the widget.

I although updated ruby to 2.1.0. I hope this is fine;) Further I added `gem sqlite3` in order to skip installing mysql. To clean things up I extended `.gitignore`.

Regards, Leif

### CODE REVIEW

**Comment by leifhanack** [comment]
@fdietz are there any plans to upgrade to ruby 2.1? Travis don't like my PR ;)

**Comment by fdietz** [comment]
Hi again and thanks for your pull request. I was on vacation and am a bit behind on answering here!

The new plugin looks great! But, how about removing the Gemfile and ruby version changes?Generally one should use separate commits for separate issues.

I plan to upgrade to ruby 2.1.0 in the future anyways. 

I want to keep the Gemfile as slim as possible therefore I don't want the sqlite gem dependency there. What was your reason in the first place to have it? I can imagine that someone would like to replace mysql with sqlite but not having both.

**Comment by leifhanack** [comment]
I'll cherry-pick the 2.1 upgrade and will offer another PR.

I haven't install mysql and don't want to:) How can I stay with sqlite while others use mysql? Is there sth like a "local" Gemfile which works but is not committed?

I thought having both in the Gemfile is the way to go. 

I will clean it up and renew the PR.

**Comment by fdietz** [comment]
The handle the Gemfile changes you prefer, I suggest you maintain your own fork of team_dashboard using sqlite only. That way you can always pull in my latest commits but keep your own Gemfile.

**Pull request closed without merging**
