### PR TITLE
Added Jira Filter-Count as Number Source

### PR DESCRIPTION
**Pull request by tubit**
Hi,

I've added a Number Widget to display the amount of tickets found by a jira search filter.

It's tested againt jira 4.4.3. 

Give it a try. :-)

### CODE REVIEW

**Comment by fdietz** [comment]
Hi Tubit,

awesome new data source plugin!

One minor thing. Can you please refactor to use the HTTPService provided by Team Dashboard instead of manually using net/http? Our goal is to provide a single point of configuration for all service calls (including ssl, proxy, authentication, error handling, url encoding/decoding, etc.) This should additionally simplify your code quite a bit.

Here is an example usage:
https://github.com/fdietz/team_dashboard/blob/master/app/models/sources/exception_tracker/errbit.rb

Thanks!

**Comment by tubit** [comment]
Hi Frederik,

sure, I'll have a look.

Cheers
Dennis

**Comment by tubit** [comment]
Hi Frederik,

are you ok with this? 

I use URI to create the URL string for HTTPService. This is because I did not want to change the way jira_url is configured.

And I removed the rspec test for this datasource. I've no clue how to fix it for travis-ci. :-( :-1:

**Comment by fdietz** [comment]
Hi tubit,

sorry for my late response, just came back from vacation.

I've merged your request and added a test spec: d2d5ababb33e0fd3f22b6357192ff4990f920419

Additionally, I've created a single markdown for all widget configuration details: e6962b52c67459e78c9baaadb196375f57a8e96f

Thanks!

**Pull request closed without merging**
