### PR TITLE
Replace dashboard locking with 'fullscreen' and 'edit' modes

### PR DESCRIPTION
**Pull request by ndbroadbent**
I didn't think it looked good to always display the nav and toolbar when the dashboard is showing on a big screen. I've removed the locking idea, and replaced it with 'fullscreen' and 'edit' modes. The toolbar and nav are hidden when the dashboard is in fullscreen mode. Clicking anywhere on the screen will take you to 'edit' mode, where they will be shown again, and you can make changes to the dashboard. 

The default `/dashboards/:id` route takes you straight to full-screen mode. I've also added a route for `/dashboards/:id/edit`, which puts the dashboard in edit mode. This let's you set up your dashboard PC to just load the fullscreen dashboard whenever it restarts. Toggling between 'fullscreen' and 'edit mode' will automatically update the URL in the browser.

### CODE REVIEW

**Comment by ndbroadbent** [comment]
I've updated this pull request to replace the dashboard locking idea with fullscreen mode.

**Comment by ndbroadbent** [comment]
One more update - have made fullscreen mode the default, and added an 'edit' route at `/dashboards/:id/edit`.

**Comment by fdietz** [comment]
Hi Nathan,

really like the full screen idea - looks much better than my previous locking idea! 

I like to discuss though your new proposed behaviour. When creating a new dashboard you automatically end up in full screen mode with an empty background. It is very confusing, I'd therefore prefer to start with the edit mode instead here. 

When switching to full screen mode, I'd expect a flash message to quickly show the user we are switching to fullscreen mode and show the user how to exit fullscreen mode.

Still pondering on the navigation to the "show" (fullscreen) and "edit" url. My feeling is that it'd be more approachable for users if we don't mix the concepts of edit/show and fullscreen. Fullscreen is in my opinion only a variation of show.

So, how about we drop the "edit" url (its a show page with in-place editing) and always navigate to the show page. The fullscreen button then toggles between different variations of show. 

That would also mean we don't need the show and edit link in the dashboard#index page.

As a side note. I've noticed that your enableFullscreen() method in dashboard.js directly changes the dom via jquery,  even tough the dom node is outside the context of the dashboard. That way the dashboard component is not a reusable component anymore. I am actually in contact with a developer who embedded Team Dashboard and this becomes more difficult now. I suggest to use instead an event broadcast about fullscreen and other components (for example the toolbar) to respond to this event accordingly. I am pretty sure I've done it wrong myself somewhere in the codebase!

Also please don't change existing migration files. Instead add new migrations to remove db columns.

Please, let me know what you think!

Cheers,
-Frederik

PS: I've started working on a new version of Team Dashboard with focus on simplifying creation of new widgets and getting rid of lots of javascript boilerplate code. I'm therefore a little bit more conservative than usually in adding new features for the time being ;-) I'm sorry that the timing collides a bit with your pull requests. I'll do my best to get your pull requests in and moving larger changes together in the new version. Have a nice weekend :-)

**Comment by ndbroadbent** [comment]
Hi Frederik,

Thanks for your feedback! I've removed the edit route, and added a `/fullscreen` route instead, so that our dashboard PC can automatically display the fullscreen board.

I''m also triggering fullscreen with events now, so you can remove the nav bar without causing any errors.

I've added a "Click anywhere to exit fullscreen." message that appears in an overlay for 1.5 seconds, when the 'fullscreen' button is clicked. I've also added the [BigScreen](https://github.com/bdougherty/BigScreen) library to actually request the browser to go into native fullscreen (same as pressing `F11` key.) This only works on the newest browsers, so I really hope you don't want to support old IE versions :)

I haven't changed any existing migrations, I added a new one and updated `db/schema.rb`.

Sounds great about the new version of Team Dashboard. Please let me know if you need any help!

**Comment by fdietz** [comment]
Hi again,

you are quick! I've looked into your changes and really like it!

One question though. Is it possible when clicking anywhere to exit full screen completely? When pressing Escape it will switch from Fullscreen to Maximized Window. Another Escape will then go back to the previous browser window dimensions. When clicking anywhere the fullscreen mode is still on and you have to press Escape to go back to the previous browser window dimensions. 

Can you change it that when clicking anywhere it also drops out of fullscreen mode completely?

Cheers!

**Comment by fdietz** [comment]
Hi again,

I've started working on the version 2 which is now on master and will look how to incorporate this in the new codebase. Keep you posted!

Cheers!

**Comment by ndbroadbent** [comment]
Hooray, my company decided that we want to have most of our tools self-hosted, so it looks like I might be quite involved with this project. I've just been playing with Geckoboard today, and was impressed by their integration options, so I would like to get a lot of those into team_dashboard.  
Look forward to trying out the new codebase and contributing some features!

**Comment by fdietz** [comment]
Great news, Nathan!

**Comment by fdietz** [comment]
Hi Nathan,

I've ported your code over to version2: 7228aa4f469546fef8252e933f9d1d2d47d33407

Thanks again! 
Frederik

**Comment by seanhoughton** [comment]
Is there a way to control this with the URL like in previous implementations? I looked through the code but I don't see anything using $location.search to read or write fullscreen parameters.

**Pull request closed without merging**
